FROM python:3.11-slim

EXPOSE 8080

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ ./src
COPY setup.py .
COPY README.md .
RUN python -m pip install .

CMD ["python", "src/ui/app.py"]
